# Generated by Django 5.2.9 on 2026-01-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва книги')),
                ('author', models.CharField(max_length=150, verbose_name='Автор')),
                ('year', models.PositiveIntegerField(verbose_name='Рік видання')),
                ('style', models.CharField(max_length=80, verbose_name='Стиль')),
                ('publisher', models.CharField(max_length=120, verbose_name='Видавництво')),
                ('is_available', models.BooleanField(default=True, verbose_name='Є в наявності')),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('phone', models.CharField(max_length=20, verbose_name='Контактний телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('joined_at', models.DateField(auto_now_add=True, verbose_name='Дата запису до бібліотеки')),
            ],
        ),
    ]
